# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from GameController import Controller
from effects import Effects
from functools import partial
import time

class Ui_MainWindow(object):
    controller = None
    state = 'not_started'
    player_turn = 1

    def updateInstruction(self):
        if self.state == 'playing':
            self.instructions.setText('Vez do jogador ' + str(self.player_turn) + ' fazer sua jogada')


    def insertValue(self, label, values, event):
        if self.state == 'not_started':
            self.state = 'playing'

        result = self.controller.setAValue(self, label, values)

        if result != 'Next' and result != 'Fail':
            self.instructions.setText(result)
            self.state = 'finished'
            self.optionsPanel.setHidden(False)
        else:
            if result == 'Fail':
                e = Effects('warning-highlight', label)
                e.start()
                e.exec()

        self.updateInstruction()

    def playAgain(self, event):
        self.controller = Controller()

        for i in range(0, self.gridLayout.count() - 1):
            if isinstance(self.gridLayout.itemAt(i).widget(), QtWidgets.QLabel):
                self.gridLayout.itemAt(i).widget().setText(' ')

        self.state = 'not_started'
        self.player_turn = 1
        self.optionsPanel.setHidden(True)

    def setupUi(self, MainWindow):
        self.controller = Controller()

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(665, 600)
        MainWindow.setFixedSize(665, 600)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(150, 200, 382, 331))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setObjectName("label")
        self.label.mousePressEvent = partial(self.insertValue, self.label, {'x':1, 'y':1})
        self.label.setCursor(QtCore.Qt.PointingHandCursor)
        self.gridLayout.addWidget(self.label, 2, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.label_4.setFont(font)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_4.mousePressEvent = partial(self.insertValue, self.label_4, {'x':2, 'y':2})
        self.label_4.setCursor(QtCore.Qt.PointingHandCursor)
        self.gridLayout.addWidget(self.label_4, 5, 4, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.label_5.setFont(font)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_5.mousePressEvent = partial(self.insertValue, self.label_5, {'x':1, 'y':0})
        self.label_5.setCursor(QtCore.Qt.PointingHandCursor)
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.label_2.setFont(font)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_2.mousePressEvent = partial(self.insertValue, self.label_2, {'x':2, 'y':0})
        self.label_2.setCursor(QtCore.Qt.PointingHandCursor)
        self.gridLayout.addWidget(self.label_2, 5, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.label_3.setFont(font)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_3.mousePressEvent = partial(self.insertValue, self.label_3, {'x':2, 'y':1})
        self.label_3.setCursor(QtCore.Qt.PointingHandCursor)
        self.gridLayout.addWidget(self.label_3, 5, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.label_6.setFont(font)
        self.label_6.setAutoFillBackground(True)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_6.mousePressEvent = partial(self.insertValue, self.label_6, {'x':0, 'y':0})
        self.label_6.setCursor(QtCore.Qt.PointingHandCursor)
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.label_7.setFont(font)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_7.mousePressEvent = partial(self.insertValue, self.label_7, {'x':0, 'y':1})
        self.label_7.setCursor(QtCore.Qt.PointingHandCursor)
        self.gridLayout.addWidget(self.label_7, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.label_8.setFont(font)
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_8.mousePressEvent = partial(self.insertValue, self.label_8, {'x':0, 'y':2})
        self.label_8.setCursor(QtCore.Qt.PointingHandCursor)
        self.gridLayout.addWidget(self.label_8, 0, 4, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.label_9.setFont(font)
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_9.mousePressEvent = partial(self.insertValue, self.label_9, {'x':1, 'y':2})
        self.label_9.setCursor(QtCore.Qt.PointingHandCursor)
        self.gridLayout.addWidget(self.label_9, 2, 4, 1, 1, QtCore.Qt.AlignHCenter)
        self.line = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 0, 1, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 0, 3, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout.addWidget(self.line_5, 2, 3, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 5, 1, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout.addWidget(self.line_6, 5, 3, 1, 1)
        self.line_9 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout.addWidget(self.line_9, 1, 4, 1, 1)
        self.line_7 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout.addWidget(self.line_7, 1, 0, 1, 1)
        self.line_8 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout.addWidget(self.line_8, 1, 2, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 2, 1, 1, 1)
        self.line_10 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.gridLayout.addWidget(self.line_10, 3, 2, 1, 1)
        self.line_11 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.gridLayout.addWidget(self.line_11, 3, 0, 1, 1)
        self.line_12 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.gridLayout.addWidget(self.line_12, 3, 4, 1, 1)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(50, 40, 591, 80))
        self.widget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.widget.setObjectName("widget")
        self.instructions = QtWidgets.QLabel(self.widget)
        self.instructions.setGeometry(QtCore.QRect(0, 5, 591, 71))
        self.instructions.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.instructions.setAlignment(QtCore.Qt.AlignCenter)
        self.instructions.setObjectName("instructions")
        MainWindow.setCentralWidget(self.centralwidget)

        self.optionsPanel = QtWidgets.QWidget(self.centralwidget)
        self.optionsPanel.move(255, 540)
        self.optionsPanel.setStyleSheet('background-color: #000099')
        self.panelLayout = QtWidgets.QHBoxLayout(self.optionsPanel)
        self.playButton = QtWidgets.QPushButton('Jogar novamente')
        self.playButton.mousePressEvent = partial(self.playAgain)
        self.playButton.setStyleSheet('background-color: #00DD00')
        self.quitButton = QtWidgets.QPushButton('Sair')
        self.quitButton.setStyleSheet('background-color: #DD0000')
        self.panelLayout.addWidget(self.playButton)
        self.panelLayout.addWidget(self.quitButton)
        self.optionsPanel.setHidden(True)

        '''self.test = QtWidgets.QPushButton('test', self.centralwidget)
        self.test.mousePressEvent = partial(self.playAgain) 
        '''

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.instructions.setText(_translate("MainWindow", "Bem vindo ao Jogo da Velha! Clique em um dos quadrados para começar."))
